Object = require "Scripts/object"
json = require "Scripts/json"
require "Scripts/vector"
require "Scripts/actor"
require "Scripts/AnimActor"
require "Scripts/ImageActor"
require "Scripts/desktop"
require "Scripts/DMenuBar"
require "Scripts/DesktopIcon"
require "Scripts/Win"
require "Scripts/window-play"
require "Scripts/Close-Btn"
require "Scripts/World"
require "Scripts/Block"
require "Scripts/DBlock"
require "Scripts/Player"
require "Scripts/ui"
require "Scripts/startmenu"
require "Scripts/startmenuicons"
require "Scripts/timer"
require "Scripts/key"
require "Scripts/Name"
require "Scripts/barrier"
require "Scripts/StartMenuItems"
require "Scripts/EndScreen"
